# permissions for end users to edit odhintegrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odhintegration-editor-role
rules:
- apiGroups:
  - odh.redhat.com
  resources:
  - odhintegrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - odh.redhat.com
  resources:
  - odhintegrations/status
  verbs:
  - get
